version: "3.8"

services:
  flask:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: inf5190_project
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
